// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blogPosts: create.doc("blogPosts", {"accessible-forms-guide.mdx": () => import("../content/blog/accessible-forms-guide.mdx?collection=blogPosts"), "build-forms-without-code.mdx": () => import("../content/blog/build-forms-without-code.mdx?collection=blogPosts"), "build-multi-step-survey.mdx": () => import("../content/blog/build-multi-step-survey.mdx?collection=blogPosts"), "conversational-forms.mdx": () => import("../content/blog/conversational-forms.mdx?collection=blogPosts"), "fieldcraft-adapters-now-open-source.mdx": () => import("../content/blog/fieldcraft-adapters-now-open-source.mdx?collection=blogPosts"), "fieldcraft-validation-pipeline.mdx": () => import("../content/blog/fieldcraft-validation-pipeline.mdx?collection=blogPosts"), "form-ux-lessons.mdx": () => import("../content/blog/form-ux-lessons.mdx?collection=blogPosts"), "introducing-fieldcraft.mdx": () => import("../content/blog/introducing-fieldcraft.mdx?collection=blogPosts"), "real-cost-building-forms.mdx": () => import("../content/blog/real-cost-building-forms.mdx?collection=blogPosts"), "schema-vs-code-driven-forms.mdx": () => import("../content/blog/schema-vs-code-driven-forms.mdx?collection=blogPosts"), "self-hosted-vs-cloud-forms.mdx": () => import("../content/blog/self-hosted-vs-cloud-forms.mdx?collection=blogPosts"), "why-schema-driven.mdx": () => import("../content/blog/why-schema-driven.mdx?collection=blogPosts"), }),
  docs: create.doc("docs", {"index.md": () => import("../content/docs/index.md?collection=docs"), "core-concepts/computed-fields.md": () => import("../content/docs/core-concepts/computed-fields.md?collection=docs"), "core-concepts/conditional-logic.md": () => import("../content/docs/core-concepts/conditional-logic.md?collection=docs"), "core-concepts/field-types.md": () => import("../content/docs/core-concepts/field-types.md?collection=docs"), "core-concepts/multi-step-forms.md": () => import("../content/docs/core-concepts/multi-step-forms.md?collection=docs"), "core-concepts/schema-anatomy.md": () => import("../content/docs/core-concepts/schema-anatomy.md?collection=docs"), "core-concepts/telemetry.md": () => import("../content/docs/core-concepts/telemetry.md?collection=docs"), "core-concepts/validation.md": () => import("../content/docs/core-concepts/validation.md?collection=docs"), "getting-started/installation.md": () => import("../content/docs/getting-started/installation.md?collection=docs"), "getting-started/project-structure.md": () => import("../content/docs/getting-started/project-structure.md?collection=docs"), "getting-started/your-first-form.md": () => import("../content/docs/getting-started/your-first-form.md?collection=docs"), "pro/licence-and-activation.md": () => import("../content/docs/pro/licence-and-activation.md?collection=docs"), "pro/templates.md": () => import("../content/docs/pro/templates.md?collection=docs"), "pro/visual-builder.md": () => import("../content/docs/pro/visual-builder.md?collection=docs"), "react/custom-field-types.md": () => import("../content/docs/react/custom-field-types.md?collection=docs"), "react/form-renderer.md": () => import("../content/docs/react/form-renderer.md?collection=docs"), "react/hooks.md": () => import("../content/docs/react/hooks.md?collection=docs"), "react/theming.md": () => import("../content/docs/react/theming.md?collection=docs"), "submission/adapters-overview.md": () => import("../content/docs/submission/adapters-overview.md?collection=docs"), "submission/drafts-and-prefill.md": () => import("../content/docs/submission/drafts-and-prefill.md?collection=docs"), "submission/server-validation.md": () => import("../content/docs/submission/server-validation.md?collection=docs"), }),
};
export default browserCollections;